### ISSUE TITLE
data never refresh

### ISSUE THREAD

**Issue by nolith** [marcelwestrahome/home-assistant-niu-component#53] opened 2023-06-28 17:56 UTC
Hello, I have installed this extension (v 2.1.3) using HACS.

It detected my scooter but it only refresh data when I reboot home assistant.

**Comment by delmeer** [comment] 2023-06-29 14:42
Same over here after migration to this version. Before, when in configuration.yaml, never had any problems.
Worked flawlessly. Marcel, could you please fix it!!!

**Comment by syssi** [comment] 2023-06-30 06:27
Are there any errors at the log?

**Comment by nolith** [comment] 2023-06-30 07:14
```
2023-06-30 09:10:27.003 WARNING (MainThread) [homeassistant.components.sensor] Updating niu sensor took longer than the scheduled update interval 0:00:30
2023-06-30 09:10:57.005 WARNING (MainThread) [homeassistant.components.sensor] Updating niu sensor took longer than the scheduled update interval 0:00:30
2023-06-30 09:11:27.005 WARNING (MainThread) [homeassistant.components.sensor] Updating niu sensor took longer than the scheduled update interval 0:00:30
2023-06-30 09:11:57.006 WARNING (MainThread) [homeassistant.components.sensor] Updating niu sensor took longer than the scheduled update interval 0:00:30
2023-06-30 09:12:27.007 WARNING (MainThread) [homeassistant.components.sensor] Updating niu sensor took longer than the scheduled update interval 0:00:30
2023-06-30 09:12:57.009 WARNING (MainThread) [homeassistant.components.sensor] Updating niu sensor took longer than the scheduled update interval 0:00:30
```

**Comment by delmeer** [comment] 2023-06-30 07:30
Logger: homeassistant.helpers.entity
Source: custom_components/niu/api.py:143
Integration: Niu Integration ([documentation](https://github.com/marcelwestrahome/home-assistant-niu-component), [issues](https://github.com/marcelwestrahome/home-assistant-niu-component/issues))
First occurred: June 29, 2023 at 21:19:18 (26 occurrences)
Last logged: 07:20:20

    Update for sensor.niu_scooter_martijns_niu_temperature fails
    Update for sensor.niu_scooter_martijns_niu_isconnected fails
    Update for sensor.niu_scooter_martijns_niu_timescharged fails
    Update for sensor.niu_scooter_martijns_niu_batterygrade fails
    Update for sensor.niu_scooter_martijns_niu_temperaturedesc fails

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in async_device_update
    await self.async_update()
  File "/config/custom_components/niu/sensor.py", line 143, in async_update
    self._state = self._api.getDataBat(self._id_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/niu/api.py", line 143, in getDataBat
    return self.dataBat["data"]["batteries"]["compartmentA"][id_field]
           ~~~~~~~~~~~~^^^^^^^^
TypeError: 'bool' object is not subscriptable

**Comment by delmeer** [comment] 2023-06-30 07:31
2023-06-29 16:24:50.299 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration niu which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-29 17:38:48.073 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.niu_scooter_martijns_niu_lasttrackaveragespeed fails
File "/config/custom_components/niu/sensor.py", line 163, in async_update
File "/config/custom_components/niu/api.py", line 169, in getDataTrack
2023-06-29 17:38:48.088 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.niu_scooter_martijns_niu_lasttrackstarttime fails
File "/config/custom_components/niu/sensor.py", line 163, in async_update
File "/config/custom_components/niu/api.py", line 160, in getDataTrack
2023-06-29 17:38:48.101 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.niu_scooter_martijns_niu_lasttrackdistance fails
File "/config/custom_components/niu/sensor.py", line 163, in async_update
File "/config/custom_components/niu/api.py", line 169, in getDataTrack
2023-06-29 21:01:18.466 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.niu_scooter_martijns_niu_lasttrackdistance fails
File "/config/custom_components/niu/sensor.py", line 163, in async_update
File "/config/custom_components/niu/api.py", line 169, in getDataTrack
2023-06-29 21:01:18.507 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.niu_scooter_martijns_niu_lasttrackendtime fails
File "/config/custom_components/niu/sensor.py", line 163, in async_update
File "/config/custom_components/niu/api.py", line 160, in getDataTrack
2023-06-29 21:01:18.544 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.niu_scooter_martijns_niu_lasttrackstarttime fails

**Comment by delmeer** [comment] 2023-06-30 07:32
Home Assistant Core
Update for sensor.niu_scooter_martijns_niu_temperature fails
07:20:20 – (ERROR) Niu Integration (custom integration) - message first occurred at June 29, 2023 at 21:19:18 and shows up 26 times
Error doing job: Task exception was never retrieved
06:18:17 – (ERROR) Niu Integration (custom integration) - message first occurred at June 29, 2023 at 21:29:16 and shows up 12 times
Update for sensor.niu_scooter_martijns_niu_lasttrackaveragespeed fails
05:57:49 – (ERROR) Niu Integration (custom integration) - message first occurred at June 29, 2023 at 17:38:48 and shows up 16 times
Update for sensor.niu_scooter_martijns_niu_lasttrackstarttime fails
05:57:49 – (ERROR) Niu Integration (custom integration) - message first occurred at June 29, 2023 at 17:38:48 and shows up 17 times
Update for sensor.niu_scooter_martijns_niu_lasttrackridingtime fails
05:41:19 – (ERROR) Niu Integration (custom integration) - message first occurred at June 29, 2023 at 21:01:18 and shows up 7 times
Update for sensor.niu_scooter_martijns_niu_totalmileage fails
05:17:18 – (ERROR) Niu Integration (custom integration) - message first occurred at June 29, 2023 at 22:29:17 and shows up 5 times

**Comment by delmeer** [comment] 2023-06-30 07:37
Logger: homeassistant
Source: custom_components/niu/api.py:143
Integration: Niu Integration ([documentation](https://github.com/marcelwestrahome/home-assistant-niu-component), [issues](https://github.com/marcelwestrahome/home-assistant-niu-component/issues))
First occurred: June 29, 2023 at 21:29:16 (12 occurrences)
Last logged: 06:18:17
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 879, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 577, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 657, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/niu/sensor.py", line 127, in extra_state_attributes
    "bmsId": self._api.getDataBat("bmsId"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/niu/api.py", line 143, in getDataBat
    return self.dataBat["data"]["batteries"]["compartmentA"][id_field]
           ~~~~~~~~~~~~^^^^^^^^
TypeError: 'bool' object is not subscriptable

**Comment by syssi** [comment] 2023-06-30 07:37
I'm able to reproduce the issue and will have a look.

**Comment by delmeer** [comment] 2023-06-30 08:17
> I'm able to reproduce the issue and will have a look.

Thanks!! Would be great if you can solve this issue.
Let me know if I need to test it for you.

**Comment by marcelwestrahome** [comment] 2023-06-30 08:58
Just to be sure, this is a scooter not a step.
Which country are you, because I do not have any problems with the last version of HA (Home Assistant 2023.6.3)...

**Comment by delmeer** [comment] 2023-06-30 09:05
Yes, NIU NQI. Live in the Netherlands.
When installing, do I need to enter the scooter ID as well?

**Comment by marcelwestrahome** [comment] 2023-06-30 09:09
yes

**Comment by delmeer** [comment] 2023-06-30 09:14
Scooter ID is the same as the serial number? Or where to find it...

**Comment by marcelwestrahome** [comment] 2023-06-30 09:51
enter  0

**Comment by nolith** [comment] 2023-06-30 09:53
Mine is a scooter as well, and I'm from Italy

**Comment by delmeer** [comment] 2023-06-30 10:28
> enter 0

That's what I already did

**Comment by marcelwestrahome** [comment] 2023-06-30 12:11
do you have two batteries in your scooters ?

**Comment by nolith** [comment] 2023-06-30 12:55
> do you have two batteries in your scooters ?
> 
> 

Mine has two. It's a NIU N-GT

**Comment by delmeer** [comment] 2023-06-30 18:08
> do you have two batteries in your scooters ?

Mine doesn’t.  I do use 2 battery’s but have to switch so they are not connected at the same time.

**Comment by delmeer** [comment] 2023-07-04 09:38
Hi guys, any progress?

**Comment by vincentnk** [comment] 2023-07-05 14:38
I enabled debug logging and found the following error:

> 2023-07-05 10:10:08.399 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.niu_scooter_de_niuris_temperature fails
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
>     httplib_response = self._make_request(
>                        ^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 403, in _make_request
>     self._validate_conn(conn)
>   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
>     conn.connect()
>   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 419, in connect
>     self.sock = ssl_wrap_socket(
>                 ^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
>     ssl_sock = _ssl_wrap_socket_impl(
>                ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
>     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
>     return self.sslsocket_class._create(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/ssl.py", line 1075, in _create
>     self.do_handshake()
>   File "/usr/local/lib/python3.11/ssl.py", line 1346, in do_handshake
>     self._sslobj.do_handshake()
> ConnectionResetError: [Errno 104] Connection reset by peer
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
>     resp = conn.urlopen(
>            ^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
>     retries = retries.increment(
>               ^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 550, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/urllib3/packages/six.py", line 769, in reraise
>     raise value.with_traceback(tb)
>   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
>     httplib_response = self._make_request(
>                        ^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 403, in _make_request
>     self._validate_conn(conn)
>   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
>     conn.connect()
>   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 419, in connect
>     self.sock = ssl_wrap_socket(
>                 ^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
>     ssl_sock = _ssl_wrap_socket_impl(
>                ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
>     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
>     return self.sslsocket_class._create(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/ssl.py", line 1075, in _create
>     self.do_handshake()
>   File "/usr/local/lib/python3.11/ssl.py", line 1346, in do_handshake
>     self._sslobj.do_handshake()
> urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

Don't know how relevant it is though.

**Comment by syssi** [comment] 2023-07-06 16:01
```
2023-07-06 17:53:57.976 DEBUG (SyncWorker_8) [custom_components.niu.api] Response: <Response [200]>
2023-07-06 17:53:57.979 DEBUG (MainThread) [custom_components.niu.api] DataTrack: {'data': {'items': [], 'track_mileage': []}, 'desc': '成功', 'status': 0, 'trace': '成功'}
2023-07-06 17:53:57.979 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.niu_scooter_n1s_lasttrackstarttime fails
Traceback (most recent call last):
  File "/home/sebastian/src/home-assistant/venv/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 695, in async_update_ha_state
    await self.async_device_update()
  File "/home/sebastian/src/home-assistant/venv/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 939, in async_device_update
    await self.async_update()
  File "/home/sebastian/.homeassistant/custom_components/niu/sensor.py", line 163, in async_update
    self._state = self._api.getDataTrack(self._id_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sebastian/.homeassistant/custom_components/niu/api.py", line 169, in getDataTrack
    (self.dataTrackInfo["data"][0][id_field]) / 1000
     ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
KeyError: 0
```

Interpretation: The data track info response is empty/incomplete. This case should be handled as invalid response:

```
{'data': {'items': [], 'track_mileage': []}, 'desc': '成功', 'status': 0, 'trace': '成功'}
```

**Comment by syssi** [comment] 2023-07-06 16:51
```
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in async_device_update
await self.async_update()
File "/config/custom_components/niu/sensor.py", line 143, in async_update
self._state = self._api.getDataBat(self._id_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/niu/api.py", line 143, in getDataBat
return self.dataBat["data"]["batteries"]["compartmentA"][id_field]
~~~~~~~~~~~~^^^^^^^^
TypeError: 'bool' object is not subscriptable
```

This seems to be another flavour of the issue. In this case `self.dataBat` is probably `false` because the `get_info` request didn't return a valid response:

```
        except ConnectionError:
            return False
        if r.status_code != 200:
            return False
        data = json.loads(r.content.decode())
        if data["status"] != 0:
            return False
        return data
```

In all (handled) errors cases the property is set to `false` instead of the response payload.

**Comment by syssi** [comment] 2023-07-06 20:36
Unstable API endpoint:

```
2023-07-06 19:55:17.606 DEBUG (SyncWorker_8) [custom_components.niu.api] get_info response: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

2023-07-06 19:55:17.608 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.niu_scooter_n1s_isconnected fails
Traceback (most recent call last):
  File "/home/sebastian/src/home-assistant/venv/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 695, in async_update_ha_state
    await self.async_device_update()
  File "/home/sebastian/src/home-assistant/venv/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 939, in async_device_update
    await self.async_update()
  File "/home/sebastian/.homeassistant/custom_components/niu/sensor.py", line 143, in async_update
    self._state = self._api.getDataBat(self._id_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sebastian/.homeassistant/custom_components/niu/api.py", line 153, in getDataBat
    return self.dataBat["data"]["batteries"]["compartmentA"][id_field]
           ~~~~~~~~~~~~^^^^^^^^
TypeError: 'bool' object is not subscriptable
```

**Comment by delmeer** [comment] 2023-07-09 09:02
Mabey it helps but in the past, before the update when entities were added from the configuration.yaml, all worked fine. Never had any issues…

**Comment by marcelwestrahome** [comment] 2023-07-10 14:16
You can always install an older version, however it seems the api calls are changed

**Comment by delmeer** [comment] 2023-08-16 13:28
Hi Marcel, did you, or any other contributor, make any progress on resolving this issue?

**Comment by marcelwestrahome** [comment] 2023-08-19 09:47
I have the idea thst also niu is working on their sight. I got Chinese characters in my notification now. And have also the same issue. Try to find some time to look

**Comment by delmeer** [comment] 2023-08-19 13:06
The issue with Chinese notifications…✔️

**Comment by b3nis** [comment] 2023-09-02 23:49
I have the same issue, only refreshing when rebooting. I have two HA instances and two scooters (well, a friends HA that I have access to). Let me know if I can contribute in any way.

**Comment by marcelwestrahome** [comment] 2023-09-06 12:53
@syssi I have the same problem sometimes :-). But it always works witha reatart, so not sure what happening here. Do you not having this issue.

**Comment by syssi** [comment] 2023-09-06 12:57
It's the same here. I will try to find some time to have a look soon.

**Comment by marcelwestrahome** [comment] 2023-09-06 13:05
> It's the same here. I will try to find some time to have a look soon.

thanks, to be honest I do not know exactly how the components is working now because the latest updates :-(

**Comment by delmeer** [comment] 2023-09-06 13:08
Sometimes it looks like some parts are updated longer than others. For sure the "last ride" information is the first thing that stops (visual) refreshing

**Comment by delmeer** [comment] 2023-09-08 08:18
Updated test environment to Home Assistant 2023.9.0 and now "Last Track Camera" isn't working anymore 
![Screenshot 2023-09-08 at 10 17 26](https://github.com/marcelwestrahome/home-assistant-niu-component/assets/73558141/5d6e081b-b6c6-4c93-9066-f0d461cbb4d6)

**Comment by jurekjure** [comment] 2023-09-18 18:49
Hey, Jure from Slovenia, same issue here - only updating on HA restart

**Comment by delmeer** [comment] 2023-10-11 07:00
Should I have any hope this issue will be solved by someone?
For what it's worth, I would really appreciate it

**Comment by pervolianinen** [comment] 2023-12-30 17:14
I use fork https://github.com/pikka97/home-assistant-niu-component (because this component not work with china mopeds) and have same error. I am did not update integration, but now data don`t came.

**Comment by pervolianinen** [comment] 2024-01-01 11:57
New information. Data updated in HA after open mobile app (work for china version).

**Comment by marcelwestrahome** [comment] 2024-01-03 14:21
I changed the refresh rate and publish this asd a beta version 2.1.6, in my configuration it works for at least 1 day. It seems that niu does not accept to much calls. Phone app also updates each x minutes

**Comment by MansonStudio** [comment] 2024-04-11 03:59
“Invalid authentication” china version

**Comment by marcelwestrahome** [comment] 2024-04-11 07:58
Sorry very difficult to help you. My version is working fine also over a few days (See picture). For me it is difficult to solve any issues with a server in China :-(. 
![niu](https://github.com/marcelwestrahome/home-assistant-niu-component/assets/34414405/f60965c4-eb8b-4eee-ab97-9533ac5d0e81)

**Comment by marcelwestrahome** [comment] 2024-05-02 08:25
See above, in the Netherlands it works fine

**Closed as completed** 2024-05-02 08:24 UTC
Labels: bug
